# Generated by Django 4.1.7 on 2023-03-23 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 10, 18, 34, 614730), verbose_name='date published'),
        ),
    ]
