# Generated by Django 3.1 on 2023-03-27 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230327_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 12, 21, 44, 791038), verbose_name='date published'),
        ),
    ]
