# Generated by Django 3.1 on 2023-03-28 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230327_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='tuturial_slug',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_slug',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 13, 29, 6, 19311), verbose_name='date published'),
        ),
    ]
